#!/bin/bash

alias_file=~/.flatalias

# Get list of Flatpak apps
app_list=$(flatpak list --app --columns=application)

# Loop through each app in the list
while read -r line; do
    # Extract app ID from line
    app_id=$(echo "$line" | awk '{print $1}')

    # Extract app name from app ID
    app_name=$(echo "$app_id" | awk -F. '{print $NF}' | tr -d '[:digit:]_-')

    # Convert app name to lowercase
    app_name=$(echo "$app_name" | tr '[:upper:]' '[:lower:]')

    # Search for app name and ID in alias_file
    if ! grep -q "$app_id" $alias_file; then
        echo "alias $app_name=\"flatpak run $app_id\"" >> $alias_file && echo "$app_name alias created in $alias_file"
    fi

done <<< "$app_list"

# Search for app name and ID in shell config files
rc_files=(~/.bashrc ~/.config/fish/config.fish ~/.zshrc)

for rc_file in "${rc_files[@]}"
do
    if [ -f ${rc_file} ]; then
        if ! grep -q "${alias_file}" $rc_file; then
            echo "source $alias_file" >> $rc_file
        fi
    fi
done
