#!/bin/bash

BINDIR=/var/lib/flatpak/exports/bin
export PATH=$PATH:$BINDIR

for app_id in $BINDIR/*; do
    # Extract app name from app ID
    app_name=$(echo "$app_id" | awk -F. '{print $NF}' | tr -d '[:digit:]_-')

    # Convert app name to lowercase
    app_name=$(echo "$app_name" | tr '[:upper:]' '[:lower:]')

    alias $app_name=$app_id
done
